name: publish npm package
permissions:
  contents: read

on:
  release:
    types: [created]

jobs:
  npm-package:
    # Do not run npm (registry.npmjs.org) publish on the fork
    if: ${{ github.repository_owner == 'codebam' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - run: npm i
      - run: npm ci
      - run: npm run lint --workspace=packages
      - run: npm run build --workspace=packages
      - run: npm publish --workspace=packages/main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
